name: Run CI checks

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, dev]

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: yarn nx affected --target=build --base=origin/main~1 --parallel
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  test:
    runs-on: ubuntu-latest
    name: Testing affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: yarn nx affected --target=test --base=origin/main~1 --parallel

  lint:
    runs-on: ubuntu-latest
    name: Linting affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: yarn nx affected --target=lint --base=origin/main~1 --parallel

  e2e:
    runs-on: ubuntu-latest
    name: E2E testing affected apps
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - name: Download a single artifact
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: yarn nx affected -- --target=e2e --base=origin/main~1 --parallel
      - run: git reset --hard
